env:
  browser: true
  node: true
  es6: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
parserOptions:
  sourceType: module
  ecmaVersion: 2020
rules:
  strict:
    - 2
    - global
  dot-notation: 0
  no-unused-expressions: 2
  no-loop-func: 2
  no-shadow: 0
  block-scoped-var: 2
  prettier/prettier:
    - "error"
    - {}
    - usePrettierrc: true
